Repository manito-project/SantaManito-iOS, pull requests merged in 2024-11, with the labels that each got.

#82 [Feat/#76] 미션하기 추가 로직 구현
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/RoomStateFactory.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/User/MatchedUserResponse.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/User/MemberResponse.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/User/UserResponse.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/Member.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/Mission.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/RoomDetail.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/User/User.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/RoomService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/ManitoWaitingRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/CheckRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditMissionViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/FinishView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/FinishViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingResultViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/SMNetworkError.swift
  SantaManito-iOS/SantaManitoUnitTests/RoomEntityTests/RoomStateFactoryTests.swift
Labels: ✨ Feature, 🐼 희재

#89 [Fix] #88 - RoomCell UI 수정
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeView.swift
Labels: 🔨 Fix

#91 [QA/#90] QA 반영하기
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Error/EnterErrorType.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/Mission.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/RoomService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/ManitoWaitingRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/ManitoWaitingRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/CheckRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/Component/SMInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditMissionView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditMissionViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/FinishViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingResultViewModel.swift
Labels: 🐼 희재, 🔨 Fix
