Repository manito-project/SantaManito-iOS, pull requests merged in 2024-10, with the labels that each got.

#44 [Feat/#43] - Home Empty뷰 구현
  SantaManito-iOS/SantaManito-iOS/Data/Service/AuthService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/RoomService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeViewModel.swift
Labels: ✨ Feature, 🐶 석우

#46 [Feat/#45] Home -> WaitingRoom -> EditRoom 엔티티 설계
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/App/Navigation/NavigationDestination.swift
  SantaManito-iOS/SantaManito-iOS/App/Navigation/NavigationRoutingView.swift
  SantaManito-iOS/SantaManito-iOS/Core/Util/SMPasteBoard.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Refresh.imageset/Contents.json
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Refresh.imageset/icRefresh.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Refresh.imageset/icRefresh@2x.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Refresh.imageset/icRefresh@3x.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Refresh.imageset/refresh_icon.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Refresh.imageset/refresh_icon@2x.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Refresh.imageset/refresh_icon@3x.png
  SantaManito-iOS/SantaManito-iOS/Data/DTO/RoomDetailResponse.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/EditRoomViewType.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/RoomDetail.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/User/User.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/EnterRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/RoomService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/ManitoWaitingRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/EnterRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/ManitoWaitingRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditRoomInfoViewModel.swift
Labels: ✨ Feature, 🐶 석우

#49 [Feat/#42] 네트워크 모듈 구현하기
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/Data/DTO/EditRoom/CreateRoomRequest.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/EditRoom/EditRoomRequest.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/EditRoom/RoomDetailResult.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/MakeRoomInfo.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/Mission.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/API/RoomAPI.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/EditRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/Service/EditRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/Service/EnterRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/Service/MatchRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Service.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/CheckRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/CheckRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Info.plist
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/APIConstants.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/BaseAPI.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/BaseService.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/Config.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/GenericResponse.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/HTTPMethod.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/Handler/ErrorHandler.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/Handler/NetworkLogHandler.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/Handler/RequestHandler.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/NetworkResponse.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/ParameterEncoding.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/Paths.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/SMNetworkError.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/URLRequestTargetType.swift
Labels: ✨ Feature, 🐼 희재

#48 Feat/#47 - Firebase Remote Config 서비스 구현
  .gitignore
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SantaManito-iOS/SantaManito-iOS/App/AppDelegate.swift
  SantaManito-iOS/SantaManito-iOS/App/SantaManito_iOSApp.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/RemoteConfigService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Test/TestView.swift
  SantaManito-iOS/SantaManito-iOS/Secret/Config.swift
  SantaManito-iOS/SantaManito-iOS/Secret/Secret.md
  SantaManito-iOS/SantaManitoUnitTests/SantaManitoUnitTests.swift
Labels: ✨ Feature, 🐶 석우

#51 Feat/#50 - 서버 점검 팝업 구현
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/App/DIContainer.swift
  SantaManito-iOS/SantaManito-iOS/App/SantaManito_iOSApp.swift
  SantaManito-iOS/SantaManito-iOS/Data/Provider/Provider.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/RemoteConfigService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Service.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashViewModel.swift
Labels: ✨ Feature, 🐶 석우

#53 Feat/#52 - 버전 업데이트 팝업 기능 구현
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/App/SantaManito_iOSApp.swift
  SantaManito-iOS/SantaManito-iOS/Core/Util/CancelBag.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/App/Version.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/AppService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/RemoteConfigService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Service.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Secret/Config.swift
  SantaManito-iOS/SantaManitoUnitTests/AppServiceTests.swift
  SantaManito-iOS/SantaManitoUnitTests/FirebaseRemoteConfigTests.swift
  SantaManito-iOS/SantaManitoUnitTests/VersionEntityTests.swift
Labels: ✨ Feature, 🐶 석우

#56 Chore/#54 - 서버 변경사항 반영
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/Core/Extension/Publisher+.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/RoomDetail.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/RoomService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/EnterRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/ManitoWaitingRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/EnterRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/ManitoWaitingRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MyPage/EditUsername/EditUsernameViewModel.swift
Labels: 🐶 석우, 🥢 Chore

#59 [Chore/#58] 전체 결과 보기 뷰 UI 수정사항 반영
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/ic_arrow.imageset/Contents.json
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/ic_arrow.imageset/Polygon 52.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/ic_arrow.imageset/Polygon 53.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/ic_arrow.imageset/Polygon 54.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Trash.imageset/Contents.json
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Trash.imageset/delete_icon 1.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Trash.imageset/delete_icon 2.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Trash.imageset/delete_icon.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Font/Font.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/Service/MatchRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/EnterRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/ManitoWaitingRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/EnterRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/CheckRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditMissionView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/CheckRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditMissionViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/FinishView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/MatchingResultView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/ShowAllResultView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/FinishViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingResultViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/ShowAllResultViewModel.swift
Labels: 🐼 희재, 🥢 Chore

#63 [Feat/#55] 방 관련 API 연결하기
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SantaManito-iOS/SantaManito-iOS/App/Navigation/NavigationRoutingView.swift
  SantaManito-iOS/SantaManito-iOS/Core/Extension/Date+.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/CreateRoomDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/EditRoomDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/EnterRoomDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/RoomDetailDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/RoomMyInfoDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Error/EnterErrorType.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/Mission.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/RoomDetail.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/User/User.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/API/RoomAPI.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/Service/EditRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/Service/EnterRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/RoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Service.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/EnterRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/ManitoWaitingRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/EnterRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/ManitoWaitingRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/CheckRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditMissionView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/FinishView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/MatchingResultView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/FinishViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingResultViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/BaseService.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/GenericResponse.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/Handler/NetworkLogHandler.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/ParameterEncoding.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/SMNetworkError.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/URLRequestTargetType.swift
Labels: ✨ Feature, 🐼 희재

#62 Fix/#61 - getAppStoreVersion() sync - > async하게 구현
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SantaManito-iOS/SantaManito-iOS.xcodeproj/xcshareddata/xcschemes/SantaManito-iOS.xcscheme
  SantaManito-iOS/SantaManito-iOS/App/Config.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/App/AppStoreResponse.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/AppService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/Service/EditRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Service.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/BaseService.swift
  SantaManito-iOS/SantaManitoUnitTests/AppServiceTests.swift
Labels: ✨ Feature, 🐶 석우

#67 Feat/#65 - RoomService 통합 + Date 로직 일부 수정
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/App/Navigation/NavigationRoutingView.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/EditRoomDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/EnterRoomDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/RoomDetailResponse.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/User/MemberResponse.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/User/UserResponse.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/EditRoomViewType.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/Member.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Auth/AuthAPI.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/Deprecated/EditRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/Deprecated/MatchRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/RoomAPI.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/RoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/Service/EditRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/RoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Service.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/EnterRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/EnterRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/ManitoWaitingRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/CheckRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/CheckRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/FinishView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/MatchingResultView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/MatchingView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/FinishViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingResultViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/APIConstants.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/BaseAPI.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/BaseService.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/SMNetworkError.swift
  SantaManito-iOS/SantaManitoUnitTests/RoomServiceServerTests.swift
Labels: ✨ Feature, 🐶 석우

#69 Feat/#68 - Room 엔티티 - DTO 및 Date 로직 처리
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/App/Navigation/NavigationRoutingView.swift
  SantaManito-iOS/SantaManito-iOS/Core/Extension/Date+.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/CreateRoomDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/EditRoomDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/MissionDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/RoomDetailDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/RoomMyInfoDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/RoomStateFactory.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/RoomDetailResponse.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/EditRoomViewType.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/MakeRoomInfo.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/Member.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/Mission.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/RoomDetail.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/User/User.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/Deprecated/EditRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/RoomService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/ManitoWaitingRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/CheckRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditMissionView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/CheckRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditMissionViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/MatchingResultView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/FinishViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingResultViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/BaseService.swift
  SantaManito-iOS/SantaManitoUnitTests/DateExtensionTests.swift
  SantaManito-iOS/SantaManitoUnitTests/RoomEntityTests/RoomDetailEntityTests.swift
  SantaManito-iOS/SantaManitoUnitTests/RoomEntityTests/RoomStateFactoryTests.swift
  SantaManito-iOS/SantaManitoUnitTests/RoomServiceServerTests.swift
Labels: ✨ Feature, 🐶 석우

#70 Feat/#64 홈뷰 API 연동 + MatchingResult, Finish 화면전환 및 엔티티 전환
  SantaManito-iOS/SantaManito-iOS/App/Navigation/NavigationDestination.swift
  SantaManito-iOS/SantaManito-iOS/App/Navigation/NavigationRoutingView.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Style/ButtonStyles.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/RoomDetailDTO.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/Room/RoomStateFactory.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/ManitoWaitingRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/ManitoWaitingRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/FinishView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/MatchingResultView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/MatchingView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/FinishViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingResultViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashViewModel.swift
Labels: ✨ Feature, 🐶 석우

#72 Feat/#71 - UserAPI 연동
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/App/DIContainer.swift
  SantaManito-iOS/SantaManito-iOS/App/Navigation/NavigationRoutingView.swift
  SantaManito-iOS/SantaManito-iOS/App/SantaManito_iOSApp.swift
  SantaManito-iOS/SantaManito-iOS/App/Window/WindowDestination.swift
  SantaManito-iOS/SantaManito-iOS/App/Window/WindowRouter.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Style/ButtonStyles.swift
  SantaManito-iOS/SantaManito-iOS/Data/DTO/User/EditNicknameReqeust.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/User/User.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Auth/AuthAPI.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Service.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/User/UserAPI.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/User/UserService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/UserDefaultsService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/UserService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MyPage/EditUsername/EditUsernameView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MyPage/EditUsername/EditUsernameViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Onboarding/OnboardingView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Onboarding/OnboardingViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Networks/Foundation/ParameterEncoding.swift
Labels: ✨ Feature, 🐶 석우
