Repository manito-project/SantaManito-iOS, pull requests merged in 2024-09, with the labels that each got.

#9 Feat/#6 공통컴포넌트 UI 구현
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/Core/Util/View/Corner.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Component/LoadingView.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Component/SMAlertView.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Component/SMScrollView.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Component/SMView.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/DSKitDemoView.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Colors.xcassets/gray2.colorset/Contents.json
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Colors.xcassets/gray3.colorset/Contents.json
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Font/Font.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Font/Pretendard-Bold.otf
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Font/Pretendard-Medium.otf
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Font/Pretendard-Regular.otf
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Font/Pretendard-SemiBold.otf
  SantaManito-iOS/SantaManito-iOS/DSKit/Style/ButtonStyles.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeView.swift
Labels: ✨ Feature, 🐶 석우

#11 [Feat/#5] 방만들기 뷰 구현
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/Core/Extension/Date+.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Component/SMColoredTextView.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/btnUnActivatedMinus.imageset/Contents.json
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/btnUnActivatedMinus.imageset/minus_icon_unactivated 1.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/btnUnActivatedMinus.imageset/minus_icon_unactivated 2.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/btnUnActivatedMinus.imageset/minus_icon_unactivated.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/btnUnActivatedPlus.imageset/Contents.json
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/btnUnActivatedPlus.imageset/plus_icon_unactivated 1.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/btnUnActivatedPlus.imageset/plus_icon_unactivated 2.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/btnUnActivatedPlus.imageset/plus_icon_unactivated.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Colors.xcassets/sm-lightbg.colorset/Contents.json
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/Component/SMInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/MakeRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/MakeRoomViewModel.swift
Labels: ✨ Feature, 🐼 희재

#17 [Feat] #16 - Splash 뷰 구현
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/App/SantaManito_iOSApp.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/AuthService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Auth/AuthView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/CancelBag.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashViewModel.swift
Labels: ✨ Feature, 🐶 석우

#18 Feat/#15 - 온보딩뷰 구현
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/DSKit/Component/SMAlertView.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Component/SMView.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkSelected.imageset/Contents.json
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkSelected.imageset/checkSelected.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkSelected.imageset/checkSelected@2x.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkSelected.imageset/checkSelected@3x.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkSelected.imageset/checked_icon.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkSelected.imageset/checked_icon@2x.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkSelected.imageset/checked_icon@3x.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkUnselected.imageset/Contents.json
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkUnselected.imageset/checkUnselected.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkUnselected.imageset/checkUnselected@2x.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkUnselected.imageset/checkUnselected@3x.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkUnselected.imageset/unchecked_icon.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkUnselected.imageset/unchecked_icon@2x.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_checkUnselected.imageset/unchecked_icon@3x.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Style/ButtonStyles.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/AuthService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/UserService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Onboarding/OnboardingView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Onboarding/OnboardingViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashViewModel.swift
Labels: ✨ Feature, 🐶 석우

#21 [Feat/#13] 방 입장하기 뷰 구현
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/App/SantaManito_iOSApp.swift
  SantaManito-iOS/SantaManito-iOS/Core/Extension/Date+.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Error.imageset/Contents.json
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Error.imageset/error_icon 1.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Error.imageset/error_icon 2.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/ic_Error.imageset/error_icon.png
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/EnterRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/ManitoRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/EnterRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/ManitoRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/MakeRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/MakeRoomViewModel.swift
Labels: ✨ Feature, 🐼 희재

#23 Feat/#19 - 홈뷰 구현
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/App/SantaManito_iOSApp.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/AuthService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/RoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Service.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashView.swift
Labels: ✨ Feature, 🐶 석우

#24 [Chore/#22] 방 만들기, 입장하기 뷰 레이아웃 수정 및 폴더링 변경 #22
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/ManitoRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/CheckRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditMissionView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/CheckRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditMissionViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditRoomInfoViewModel.swift
Labels: 🐼 희재, 🥢 Chore

#28 [Feat/#25] 방 만들기 뷰 비즈니스 로직 구체화
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/Data/Entity/MakeRoom/MakeRoomInfo.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/MakeRoom/Mission.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/MakeRoom/Room.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/EditRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/RoomService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/CheckRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditMissionView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/CheckRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditMissionViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditRoomInfoViewModel.swift
Labels: ✨ Feature, 🐼 희재

#37 [Fix/#36] Git Conflict 이슈로 인한 브랜치 이동 작업
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/Core/Extension/Date+.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/Graphics/graphics_Roulette.imageset/Contents.json
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/Graphics/graphics_Roulette.imageset/roulette 1.svg
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/Graphics/graphics_Roulette.imageset/roulette 2.svg
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/Graphics/graphics_Roulette.imageset/roulette.svg
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Font/Font.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/EditRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/MatchRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/FinishView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/MatchingResultView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/MatchingView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/ShowAllResultView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/FinishViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingResultViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/ShowAllResultViewModel.swift
Labels: 🐼 희재, 🔨 Fix

#34 Feat/#31 - 마이페이지뷰 구현하기
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/App/DIContainer.swift
  SantaManito-iOS/SantaManito-iOS/App/Navigation/NavigationDestination.swift
  SantaManito-iOS/SantaManito-iOS/App/Navigation/NavigationRoutingView.swift
  SantaManito-iOS/SantaManito-iOS/App/SantaManito_iOSApp.swift
  SantaManito-iOS/SantaManito-iOS/Core/Extension/Extension.swift
  SantaManito-iOS/SantaManito-iOS/Core/Util/View/SMWebView.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Component/LoadingView.swift
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/btnPerson.imageset/Contents.json
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/btnPerson.imageset/btnPerson.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/btnPerson.imageset/mypage_icon@2x.png
  SantaManito-iOS/SantaManito-iOS/DSKit/Resource/Assets.xcassets/btn/btnPerson.imageset/mypage_icon@3x.png
  SantaManito-iOS/SantaManito-iOS/Data/DTO/UserResponse.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/MyPage/MyPageItem.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/MakeRoomInfo.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/Mission.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/RoomDetail.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/Room/RoomState.swift
  SantaManito-iOS/SantaManito-iOS/Data/Entity/User/User.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/UserService.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/EnterRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Home/HomeView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MyPage/EditUsername/EditUsernameView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MyPage/EditUsername/EditUsernameViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MyPage/MyPage/MyPageView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MyPage/MyPage/MyPageViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Onboarding/OnboardingView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/Splash/SplashView.swift
Labels: ✨ Feature

#38 [Feat/#35] 방 만들기, 방 입장하기, 매칭하기 화면 전환 로직 구현하기
  SantaManito-iOS/SantaManito-iOS.xcodeproj/project.pbxproj
  SantaManito-iOS/SantaManito-iOS/App/Navigation/NavigationDestination.swift
  SantaManito-iOS/SantaManito-iOS/App/Navigation/NavigationRoutingView.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Room/EnterRoomService.swift
  SantaManito-iOS/SantaManito-iOS/Data/Service/Service.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/EnterRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/View/ManitoWaitingRoomView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/EnterRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/EnterRoom/ViewModel/ManitoWaitingRoomViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/CheckRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditMissionView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/View/EditRoomInfoView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditMissionViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MakeRoom/ViewModel/EditRoomInfoViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/MatchingResultView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/View/MatchingView.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingResultViewModel.swift
  SantaManito-iOS/SantaManito-iOS/Feature/MatchRoom/ViewModel/MatchingViewModel.swift
Labels: ✨ Feature, 🐼 희재
